import json, hmac, hashlib, math, copy, aiohttp, os
import sources.config as config
from datetime import datetime, timezone
from typing import List, Tuple, Optional, Dict
from utils.tools import isValidSignal
from sources.config import ln, signal_template
from utils.logger import adminReport
from decimal import Decimal, ROUND_DOWN, ROUND_UP, ROUND_FLOOR
from typing import List

# Constants
# BYBIT_BASE = "https://api.bybit.com"  # change to api-demo.bybit.com for demo
# BYBIT_BASE_DEMO = "https://api-demo.bybit.com"
# DEFAULT_BASE = BYBIT_BASE_DEMO  # use demo by default; change to BYBIT_BASE in production
# LOG_DIR = "/home/botuser/bot/logs"
# POSITIONS_FILE = "logs/positions.json"

# --- Helpers ---


def getSecretsFromSignal(signal: dict) -> Tuple[Optional[str], Optional[str]]:
    """Extract API key and secret from signal dict."""
    keys = signal.get("keys", {})
    api_key = keys.get("api_key")
    api_secret = keys.get("api_secret")
    return api_key, api_secret


def _utc_now() -> datetime:
    """Return timezone-aware current UTC datetime."""
    return datetime.now(timezone.utc)


# def price_normalize(value, step):
#     value = Decimal(str(value))
#     step = Decimal(str(step))
#     return str((value // step) * step)


def D(x):
    return Decimal(str(x))


def floorToStepDec(value, step) -> Decimal:
    value = Decimal(str(value))
    step = Decimal(str(step))

    if step == 0:
        return value

    units = (value / step).to_integral_value(rounding=ROUND_DOWN)
    return units * step


def ceilUnits(q: Decimal, step: Decimal) -> int:
    if step == 0:
        return 0
    units = (q / step).to_integral_value(rounding=ROUND_DOWN)
    if units * step < q:
        units = units + 1
    return int(units)


async def saveTradeSnapshot(placedOrders: list):
    """
    Save trade snapshot (State Machine ready).
    """

    savePath = "./logs/trades.json"
    os.makedirs(os.path.dirname(savePath), exist_ok=True)

    
    # Load existing file
    if os.path.exists(savePath):
        try:
            with open(savePath, "r", encoding="utf-8") as f:
                allTrades = json.load(f)
        except Exception:
            allTrades = {}
    else:
        allTrades = {}

    if not placedOrders:
        raise ValueError("placedOrders is empty")

    mainOrder = next(
        (o for o in placedOrders if o["variant"] == "main"),
        None,
    )

    if not mainOrder:
        raise ValueError("Main order not found")

    symbol = mainOrder["symbol"]

    entries = []
    totalQty = 0.0
    
    # Build entries
    for order in placedOrders:

        qty = float(order.get("qty") or 0)
        price = float(order.get("price") or 0)

        totalQty += qty

        entries.append(
            {
                "variant": order["variant"],
                "price": price,
                "qty": qty,

                "orderId": order["order_id"],

                # updated by syncTradeState()
                "filled": False,
                "cancelled": False,

                "fillPrice": None,
                "fillQty": 0.0,
            }
        )

    # Qty
    step = float(mainOrder["step"])
    totalQty = float(floorToStepDec(totalQty, step))
    
    # Take Profits
    takeProfits = [
        float(tp)
        for tp in (mainOrder.get("takeProfits") or [])
    ]
    
    if mainOrder["side"].lower() == "buy":
        takeProfits.sort()
    else:
        takeProfits.sort(reverse=True)

    tpOrders = []

    for i, tp in enumerate(takeProfits):
        tpOrders.append(
            {
                "index": i,

                "price": tp,

                # later generated by allocate_tp_qtys()
                "qty": None,

                "orderId": None,

                "placed": False,
                "filled": False,
                "cancelled": False,
            }
        )

    stopLoss = float(mainOrder.get("stopLoss") or 0)

    tradeSummary = {

        # Identification
        "symbol": symbol,
        "source": mainOrder["source"],

        "side": mainOrder["side"],

        "state": "waiting_entry",

        # Exchange info
        "category": mainOrder["category"],
        "marginMode": mainOrder["margin_mode"],
        "leverage": mainOrder["leverage"],

        # Instrument limits
        "minQty": float(mainOrder["minQty"]),
        "maxQty": float(mainOrder["maxQty"]),
        "step": float(mainOrder["step"]),
        "maxTrailing": float(mainOrder["maxTrailing"]),

        # Planned Trade
        "entry": float(mainOrder["price"]),

        "qty": totalQty,

        "entries": entries,

        # Current Position
        "position": {
            "opened": False,
            "qty": 0.0,
            "avgPrice": None,
            "side": None,
        },

        # Stop Loss
        "SLPrice": stopLoss,
        "SLNow": stopLoss,

        "slOrderId": None,

        # Take Profits
        "tpIndexHit": 0,

        "tpOrders": tpOrders,

        # Metadata
        "createdAt": datetime.now(timezone.utc).isoformat(),

        "updatedAt": datetime.now(timezone.utc).isoformat(),
    }

    allTrades[symbol] = tradeSummary
    
    await adminReport(f"All trades for save is: \n{allTrades}")

    with open(savePath, "w", encoding="utf-8") as f:
        json.dump(
            allTrades,
            f,
            indent=2,
            ensure_ascii=False,
        )

    await adminReport(f"✅ Trade {symbol} saved.")

    return tradeSummary


async def _aio_get(
    session: aiohttp.ClientSession,
    server: str,
    params: dict = None,
    headers: dict = None,
):
    try:
        async with session.get(
            server, params=params, headers=headers, timeout=20
        ) as resp:
            text = await resp.text()
            try:
                return json.loads(text)
            except Exception:
                await adminReport(f"⚠️ Non-JSON response from {server}: {text}")
                return None
    except Exception as e:
        await adminReport(f"❌ HTTP GET failed {server}: {e}")
        return None


async def _aio_post(
    session: aiohttp.ClientSession, server: str, payload: dict, headers: dict = None
):
    try:
        async with session.post(
            server, json=payload, headers=headers, timeout=20
        ) as resp:
            text = await resp.text()
            try:
                return json.loads(text)
            except Exception:
                await adminReport(f"⚠️ Non-JSON POST response from {server}: {text}")
                return None
    except Exception as e:
        await adminReport(f"❌ HTTP POST failed {server}: {e}")
        return None


# --- Bybit specific utilities ---
async def getBybitServerTimeMS(session: aiohttp.ClientSession, server: str) -> int:
    """Get Bybit server time in milliseconds (async)."""
    url = server + "/v5/market/time"
    res = await _aio_get(session, url)
    if res and isinstance(res, dict) and "time" in res:
        return int(res["time"])
    # fallback to local time
    return int(datetime.now(timezone.utc).timestamp() * 1000)


async def getSymbolRules(signal) -> dict:
    """
    Fetch symbol trading rules from Bybit:
    - min_qty
    - max_qty
    - qty_step
    - max_trailing_stop (callback rate for trailing orders)
    """

    session = signal.get("session")
    symbol = signal.get("symbol")

    baseURL = signal.get("exchangeURL")
    endPoint = "/v5/market/instruments-info"
    url = baseURL + endPoint

    params = {"category": "linear", "symbol": symbol}

    async with session.get(url, params=params) as resp:
        data = await resp.json()

    if data.get("retCode") != 0:
        raise ValueError(f"Failed to fetch rules for {symbol}: {data}")

    info = data["result"]["list"][0]

    lot_size_filter = info.get("lotSizeFilter", {})
    min_qty = float(lot_size_filter.get("minOrderQty", 0.0))
    max_qty = float(lot_size_filter.get("maxOrderQty", 0.0))
    step = float(lot_size_filter.get("qtyStep", 0.0))

    # trailing filter might be nested differently or missing
    trailing_filter = info.get("trailingStop", {}) or info.get("trailingStopFilter", {})
    max_trailing = float(
        trailing_filter.get("maxTrailingActive", 0.2)
    )  # fallback = 0.2

    return {
        "min_qty": min_qty,
        "max_qty": max_qty,
        "step": step,
        "max_trailing": max_trailing,
    }


# def adjust_qty_to_step(raw_qty: float, step: float) -> float:
#     """Round raw_qty to the nearest multiple of step."""
#     return raw_qty - (raw_qty % step)


async def getCurrentPrice(signal) -> float:
    """Get current last price for symbol (async)."""
    session = signal.get("session")
    symbol = signal.get("symbol")

    baseURL = signal.get("exchangeURL")
    endPoint = "/v5/market/tickers"
    url = baseURL + endPoint

    params = {"category": "linear", "symbol": symbol.upper()}

    res = await _aio_get(session, url, params=params)

    try:
        return float(res["result"]["list"][0]["lastPrice"])
    except Exception as e:
        await adminReport(f"❌ Error fetching price for {symbol}: {e}")
        return 0.0


# --- Balance & qty helpers ---
async def getUSDTBalance(signal: dict) -> float:
    """Fetch USDT unified wallet available balance (async)."""
    # await adminReport(f"Signal from getUSDTBalance \n {signal}")
    try:
        session = signal.get("session")

        baseURL = signal.get("exchangeURL")
        endPoint = "/v5/account/wallet-balance"
        url = baseURL + endPoint

        recv_window = 20000
        timestamp = await getBybitServerTimeMS(session, baseURL)

        api_key, api_secret = getSecretsFromSignal(signal)
        if not api_key or not api_secret:
            await adminReport("❌ No API key/secret provided for balance call")
            return 0.0

        params = {"accountType": "UNIFIED"}
        query_string = "accountType=UNIFIED"

        origin_string = str(timestamp) + api_key + str(recv_window) + query_string
        signature = hmac.new(
            api_secret.encode("utf-8"), origin_string.encode("utf-8"), hashlib.sha256
        ).hexdigest()

        headers = {
            "X-BAPI-API-KEY": api_key,
            "X-BAPI-SIGN": signature,
            "X-BAPI-TIMESTAMP": str(timestamp),
            "X-BAPI-RECV-WINDOW": str(recv_window),
        }

        balance_response = await _aio_get(session, url, params=params, headers=headers)
        balance_data = balance_response["result"]["list"][0]["coin"]

        usdt_balance = next(
            (item["walletBalance"] for item in balance_data if item["coin"] == "USDT"),
            None,
        )
        # await adminReport(f"💰 Balance response: {balance_response}")

        balance = float(usdt_balance) if usdt_balance is not None else 0.0
        return balance

    except Exception as e:
        await adminReport(f"❌ Error getting USDT balance: {e}")
        return 0.0


async def getQtyFromUSD(signal, usd_amount: float) -> str:
    """
    Convert USD amount to base qty using current price, step, and min_qty.
    Uses Decimal for precision and rounds based on trade side:
        - 'buy'  => ROUND_DOWN  (avoid overspending)
        - 'sell' => ROUND_UP    (ensure full closure)
    Returns formatted qty as string (e.g. '0.008', '1.000').
    """
    session = signal.get("session")
    symbol = signal.get("symbol")
    baseURL = signal.get("exchangeURL")
    side = str(signal.get("side", "buy")).lower()  # default buy if missing

    try:
        price = await getCurrentPrice(signal)
        if not price or price <= 0:
            await adminReport(
                f"❌ Invalid price for {symbol} when calculating qty (price={price})"
            )
            return "0.00"

        # تبدیل به Decimal برای دقت بالا
        usd_amount_d = Decimal(str(usd_amount))
        price_d = Decimal(str(price))
        step_d = Decimal(str(signal.get("step", "0.001")))
        min_qty_d = Decimal(str(signal.get("minQty", "0.001")))

        # --- محاسبه مقدار خام ---
        raw_qty = usd_amount_d / price_d

        # انتخاب نوع گرد کردن بر اساس نوع معامله
        rounding_mode = ROUND_DOWN if side == "buy" else ROUND_UP

        # محاسبه گام‌ها و مقدار نهایی
        steps = (raw_qty / step_d).to_integral_value(rounding=rounding_mode)
        adjusted_qty = steps * step_d

        # اطمینان از رعایت حداقل مقدار
        if adjusted_qty < min_qty_d:
            adjusted_qty = min_qty_d
            await adminReport(
                f"⚠️ {symbol}: Adjusted qty below min_qty, set to {min_qty_d}"
            )

        # تعیین تعداد اعشار بر اساس step
        decimals = abs(int(math.log10(float(step_d)))) if step_d < 1 else 0
        qty_formatted = f"{adjusted_qty:.{decimals}f}"

        # await adminReport(
        #     f"🧮 {symbol} | {side.upper()} | usd={usd_amount_d} | price={price_d} | "
        #     f"min_qty={min_qty_d} | step={step_d} | adjusted={adjusted_qty} | "
        #     f"qty_formatted={qty_formatted}"
        # )

        return qty_formatted

    except Exception as e:
        await adminReport(f"❌ Error in getQtyFromUSD for {symbol}: {e}")
        return "0.00"


# ****************************************************************************************************


async def getTradeAamountFromBalance(signal) -> str:
    # await adminReport(f"Calculating trade amount from balance:\n{signal}")

    # percent
    percent_raw = signal.get("qtyPercent", config.trade_percent)
    percent = Decimal(str(percent_raw))

    # step
    step_raw = signal.get("step")

    if not step_raw:
        await adminReport("⚠️ Step is missing or empty.")
        return "0.00"

    step = Decimal(str(step_raw))

    if step <= 0:
        await adminReport(f"⚠️ Invalid step value: {step}")
        return "0.00"

    # balance
    balance = await getUSDTBalance(signal)

    if not balance:
        await adminReport("❌ USDT balance is zero or error fetching it.")
        return "0.00"

    balance = Decimal(str(balance))

    trade_amount = floorToStepDec(balance * percent, step)

    trade_amount_str = format(trade_amount, "f")

    await adminReport(
        f"💰 Current available balance: {balance} USDT\n"
        f"➡️ Allocated {trade_amount_str} USDT for this trade ({percent * 100}%)"
    )

    return trade_amount_str


def signRequest(params: dict, api_secret: str) -> str:
    """Generate Bybit v5 signature."""
    # Convert all values to string (Booleans -> 'true'/'false')
    param_str_dict = {
        k: str(v).lower() if isinstance(v, bool) else str(v) for k, v in params.items()
    }
    # Sort params alphabetically by key
    param_str = "&".join([f"{k}={v}" for k, v in sorted(param_str_dict.items())])
    # Generate HMAC SHA256
    return hmac.new(
        api_secret.encode("utf-8"), param_str.encode("utf-8"), hashlib.sha256
    ).hexdigest()


async def setMarginAndLeverage(signal: dict) -> dict:
    session = signal.get("session")
    baseURL = signal.get("exchangeURL")
    api_key, api_secret = getSecretsFromSignal(signal)
    symbol = signal.get("symbol")
    leverage = int(signal.get("leverage", 1))
    isolated = signal.get("margin_mode", "isolated").lower() == "isolated"
    category = signal.get("category", "linear")

    # --- 1) set leverage ---
    payload_lev = {
        "api_key": api_key,
        "timestamp": await getBybitServerTimeMS(session, baseURL),
        "category": category,
        "symbol": symbol,
        "buyLeverage": str(leverage),
        "sellLeverage": str(leverage),
    }
    payload_lev["sign"] = signRequest(payload_lev, api_secret)

    endPoint = "/v5/position/set-leverage"
    url = baseURL + endPoint

    async with session.post(url, data=payload_lev) as resp:
        res_lev = await resp.json()

    # --- 2) set margin mode ---
    payload_margin = {
        "api_key": api_key,
        "timestamp": await getBybitServerTimeMS(session, baseURL),
        "category": category,
        "symbol": symbol,
        "tradeMode": 1 if isolated else 0,  # 1=isolated, 0=cross
    }
    payload_margin["sign"] = signRequest(payload_margin, api_secret)

    endPoint = "/v5/position/switch-isolated"
    url = baseURL + endPoint

    async with session.post(url, data=payload_margin) as resp:
        res_margin = await resp.json()

    return {"leverage": res_lev, "margin": res_margin}


async def getPosition(signal: dict) -> Optional[dict]:
    """
    ✅ Get open position for a symbol (Bybit v5)
    Uses the shared aiohttp session passed as argument.
    """
    session = signal.get("session")
    api_key, api_secret = getSecretsFromSignal(signal)
    symbol = signal.get("symbol")

    baseURL = signal.get("exchangeURL")
    endPoint = "/v5/position/list"
    url = baseURL + endPoint

    # گرفتن زمان سرور با همان session
    timestamp = await getBybitServerTimeMS(session, baseURL)
    if not timestamp:
        await adminReport("⚠️ getBybitServerTimeMS returned None!")
        return None

    # پارامترهای لازم برای امضا
    params = {
        "api_key": api_key,
        "category": "linear",
        "symbol": symbol.upper(),
        "timestamp": timestamp,
        "recv_window": "5000",
    }

    # ساخت امضا
    signature = signRequest(params, api_secret)
    params["sign"] = signature

    try:
        async with session.get(url, params=params) as resp:
            try:
                data = await resp.json()
            except Exception:
                text = await resp.text()
                await adminReport(f"⚠️ Invalid JSON response: {text}")
                return None

            if not isinstance(data, dict):
                await adminReport(f"⚠️ Unexpected data type: {type(data)} -> {data}")
                return None

            if data.get("retCode") != 0:
                await adminReport(
                    f"⚠️ Bybit error {data.get('retCode')}: {data.get('retMsg')}"
                )
                await adminReport(f"🔍 URL: {resp.url}")
                return None

            positions = data.get("result", {}).get("list", [])
            if not positions:
                await adminReport(f"ℹ️ No open positions found for {symbol}")
                return None

            for pos in positions:
                if (
                    pos.get("symbol") == symbol.upper()
                    and float(pos.get("size", 0)) != 0
                ):
                    return pos

            # await adminReport(
            #     f"ℹ️ Position list exists but no active position found for {symbol}"
            # )
            return None

    except Exception as e:
        await adminReport(f"ByBit:  : {ln()} ❌ getPosition error for {symbol}: {e}")
        return None


async def getOpenOrders(signal: dict) -> List[dict]:
    """
    ✅ Query open orders for a symbol using Bybit v5 REST API
    (GET /v5/order/realtime)
    """
    session = signal.get("session")
    api_key, api_secret = getSecretsFromSignal(signal)
    symbol = signal.get("symbol")
    category = signal.get("category", "linear")

    baseURL = signal.get("exchangeURL")
    endPoint = "/v5/order/realtime"
    url = baseURL + endPoint

    # گرفتن زمان سرور
    timestamp = await getBybitServerTimeMS(session, baseURL)
    if not timestamp:
        await adminReport("⚠️ getBybitServerTimeMS returned None!")
        return []

    # پارامترها برای امضا و درخواست
    params = {
        "api_key": api_key,
        "category": category,
        "symbol": symbol.upper(),
        "openOnly": "0",  # همه سفارش‌ها، نه فقط بازها
        "limit": "50",
        "timestamp": timestamp,
        "recv_window": "5000",
    }

    # ساخت امضا با تابع موجود
    signature = signRequest(params, api_secret)
    params["sign"] = signature

    try:
        async with session.get(url, params=params) as resp:
            status = resp.status
            text = await resp.text()

            if not text or text.strip() in ["null", "None"]:
                await adminReport(f"⚠️ Empty/Null response from Bybit ({status})")
                await adminReport(f"🔍 URL: {resp.url}")
                return []

            try:
                data = json.loads(text)
            except json.JSONDecodeError:
                await adminReport(f"⚠️ Invalid JSON response: {text}")
                return []

            if data.get("retCode") != 0:
                await adminReport(
                    f"⚠️ Bybit error {data.get('retCode')}: {data.get('retMsg')}"
                )
                await adminReport(f"🔍 URL: {resp.url}")
                return []

            result = data.get("result", {})
            if not isinstance(result, dict):
                await adminReport(f"⚠️ Unexpected result type: {type(result)}")
                return []

            orders = result.get("list", [])
            if not orders:
                await adminReport(f"ℹ️ No open orders found for {symbol}")
                return []
            
            # await adminReport(f"Get Open Orders:\n{json.dumps(data, indent=2)}")

            return orders

    except Exception as e:
        await adminReport(f"❌ getOpenOrders error for {symbol}: {e}")
        return []


async def allocateUSDToEntries(
    signal: dict,
    clean_entries: list,
    base_ratio: Decimal = Decimal("0.5"),  # entry اول نصف دومی
):
    total_usd = Decimal(str(signal.get("qty") or "0"))
    side_raw = signal.get("side", "").lower()
    is_long = side_raw in ("buy", "long")

    entries = [Decimal(str(e)) for e in clean_entries]
    if len(entries) != 2:
        raise ValueError("This strategy supports exactly 2 entries")

    P1, P2 = entries

    distance = abs(P1 - P2)
    ref_price = max(P1, P2)

    # ضریب فاصله (هرچه فاصله بیشتر → وزن بیشتر)
    distance_factor = Decimal("1") + (distance / ref_price)

    if is_long:
        w1 = base_ratio
        w2 = Decimal("1") * distance_factor
    else:  # SELL
        w1 = Decimal("1") * distance_factor
        w2 = base_ratio

    sum_w = w1 + w2

    A1 = (total_usd * w1 / sum_w).quantize(Decimal("0.01"), rounding=ROUND_DOWN)
    A2 = total_usd - A1

    return [A1, A2]


async def signalDivider(signal: dict) -> List[dict]:

    # Get current price and validate
    currentPrice = await getCurrentPrice(signal)
    if not currentPrice or currentPrice <= 0:
        await adminReport(
            f"❌ Invalid current price for signalDivider: {currentPrice}"
        )
        return []

    # Get and validate side
    side = str(signal.get("side")).lower()
    if side not in ["buy", "sell"]:
        await adminReport(f"⚠️ No side in signalDivider: {signal}")
        return []

    # Get step from signal or default to 0.001
    step = signal.get("step")
    if not step or step <= 0:
        await adminReport(f"⚠️ Invalid step value in signalDivider: {step}")
        return []

    # Extract and validate entries
    entries = signal.get("entry", [])
    await adminReport(f"Original entries from signal: {entries}")

    if not entries:
        return []

    if not isinstance(entries, list):
        entries = [entries]

    # Clean numeric entries and sort based on side
    clean_entries = entries
    # clean_entries = []
    # for e in entries:
    #     try:
    #         # await adminReport(f"Processing entry: {e} with step {step}")
    #         # floored = floorToStepDec(Decimal(str(e)), Decimal(str(step)))
    #         # await adminReport(f"Floored entry: {floored}")
    #         # clean_entries.append(str(floored))

    #         # clean_entries.append(float(e))
    #         clean_entries.append(str(e))
    #     except (TypeError, ValueError):
    #         continue
    # if not clean_entries:
    #     return []

    if side == "buy":
        clean_entries.sort(
            reverse=True
        )  # Sort descending for Buy (closest to farthest above current price)
    else:
        clean_entries.sort()  # Sort ascending for Sell (closest to farthest below current price)

    await adminReport(f"Cleaned and sorted entries: {clean_entries}")

    # End of cleaning and sorting entries

    # Start of quantity allocation logic based on distance and total USD amount
    # total_usd = Decimal(str(signal.get("qty") or "0"))
    min_qty = signal.get("minQty")

    # # Initial weights
    # distances = [abs(Decimal(str(e)) - Decimal(str(currentPrice))) for e in clean_entries]
    # weights = [1 / (d if d != 0 else 0.0001) for d in distances]

    # # Normalize
    # sum_weights = sum(weights)
    # usd_allocs = [round(total_usd * w / sum_weights, 2) for w in weights]

    usd_allocs = await allocateUSDToEntries(signal, clean_entries)

    # Convert to qty
    qtys = []
    for usd in usd_allocs:
        qty = await getQtyFromUSD(signal, usd)
        if qty and float(qty) >= min_qty:
            qtys.append(qty)

    await adminReport(
        f"USD allocations: {usd_allocs}\nQtys after conversion: {qtys} for {signal.get('symbol')}"
    )
    # End of quantity allocation logic

    session = signal.get("session")
    signal["session"] = None

    # Build signals
    preparedSignals = []
    for idx, (e, q) in enumerate(zip(clean_entries, qtys)):
        new_signal = copy.deepcopy(signal)
        new_signal["session"] = session
        new_signal["entry"] = [e]
        new_signal["index"] = idx
        new_signal["qty"] = str(q)
        preparedSignals.append(new_signal)

    signal["session"] = session

    # Sort by closeness
    # preparedSignals.sort(key=lambda s: abs(s["entry"][0] - currentPrice))

    # Assign roles
    for idx, sig in enumerate(preparedSignals):
        if idx == 0:
            sig["variant"] = "main"
            sig["orderType"] = "Limit"  # sig["orderType"] = "Market"
            sig["price"] = clean_entries[idx]  # signal.get("entry", [])[0] #None
            sig["takeProfits"] = signal.get("takeProfits")  # only first TP for main
            sig["stopLoss"] = signal.get("stopLoss")
        else:
            sig["variant"] = f"alt{idx}"
            sig["orderType"] = "Limit"
            sig["price"] = clean_entries[
                idx
            ]  # signal.get("entry", [])[1]  # use second entry price if exists
            sig["takeProfits"] = None
            sig["stopLoss"] = None

    # for sig in preparedSignals:
    #     await adminReport(f"Prepared divided {sig['variant']} signal: \n {sig}")

    return preparedSignals


async def getPositionQty(signal):
    """
    Get current open position quantity for a given symbol from Bybit.
    Returns float qty or None if no position is found.
    """
    session = signal.get("session")

    baseURL = signal.get("exchangeURL")
    endPoint = "/v5/position/list"
    url = baseURL + endPoint

    api_key, api_secret = getSecretsFromSignal(signal)
    symbol = signal.get("symbol")

    payload = {
        "api_key": api_key,
        "symbol": symbol,
        "category": "linear",
        "timestamp": await getBybitServerTimeMS(session, baseURL),
        "recv_window": 20000,
    }

    # Sign request
    payload["sign"] = signRequest(payload, api_secret)

    res = await _aio_get(session, url, params=payload)

    if not res or res.get("retCode") != 0:
        return None

    positions = res.get("result", {}).get("list", [])
    if not positions:
        return None

    # Extract size of the first matching position
    qty = positions[0].get("size")
    return float(qty) if qty else None


# ==== تخصیص ایمن ====
# def allocate_tp_qtys(
#     total_qty: float, takeProfits: List[float], min_qty: float, step: float
# ) -> Tuple[List[float], Dict]:
#     total = D(total_qty)
#     mind = D(min_qty)
#     stepd = D(step) if step else D("0")
#     n = len(takeProfits)

#     if n == 0:
#         return [], {"error": "no takeProfits"}

#     # وزن‌ها
#     if n == 1:
#         weights = [D("1")]
#     elif n == 2:
#         weights = [D("0.7"), D("0.3")]
#     elif n == 3:
#         weights = [D("0.5"), D("0.3"), D("0.2")]
#     else:
#         raw = [D(1) / (D(i + 1)) for i in range(n)]
#         s = sum(raw)
#         weights = [r / s for r in raw]

#     desired = [total * w for w in weights]

#     # مرحله اول: گرد کردن پایین به step
#     first_adj = []
#     for i in range(max(0, n - 1)):
#         q = desired[i]
#         qf = floorToStepDec(q, stepd)
#         if qf < 0:
#             qf = D("0")
#         first_adj.append(qf)
#     sum_first = sum(first_adj) if first_adj else D("0")

#     # آخرین TP = باقی‌مانده
#     last_adj = floorToStepDec(total - sum_first, stepd)
#     if last_adj < 0:
#         last_adj = D("0")

#     # افزایش TPهای زیر min_qty در صورت امکان (با برداشت از آخرین TP)
#     for i in range(len(first_adj)):
#         if first_adj[i] >= mind:
#             continue
#         need = mind - first_adj[i]
#         needed_units = ceilUnits(need, stepd)
#         available_units = (
#             int(((last_adj - mind) / stepd).to_integral_value(rounding=ROUND_DOWN))
#             if (last_adj > mind)
#             else 0
#         )
#         transfer_units = min(needed_units, available_units)
#         if transfer_units > 0:
#             transfer = stepd * transfer_units
#             first_adj[i] += transfer
#             last_adj -= transfer

#     if n == 1:
#         last_adj = floorToStepDec(total, stepd)

#     qtys_dec = first_adj + [last_adj] if n > 1 else [last_adj]
#     qtys_out, created_mask = [], []

#     for qd in qtys_dec:
#         if qd >= mind and qd > 0:
#             qtys_out.append(float(qd))
#             created_mask.append(True)
#         else:
#             qtys_out.append(0.0)
#             created_mask.append(False)

#     sum_alloc = sum(qtys_out)
#     leftover = float(max(D("0"), total - D(str(sum_alloc))))

#     report = {
#         "sum_allocated": float(sum_alloc),
#         "leftover": leftover,
#         "created_mask": created_mask,
#         "notes": "TPs preserved; orders created only where qty >= min_qty after step rounding.",
#     }

#     return qtys_out, report


def generateRatioList(n):
    values = [1 / (i + 1) for i in range(n)]
    total = sum(values)
    normalized = [round(v / total, 2) for v in values]

    # For ensuring sum to 1.0 after rounding
    diff = 1 - sum(normalized)
    normalized[0] += diff  # Adjust the first element to fix rounding error
    return normalized


def splitQtyByWeights(total_qty, weights, min_qty, step=None) -> List[float]:
    """
    Split total_qty into parts according to weights, ensuring:
    - each part is a multiple of `step` (or min_qty if step not given)
    - total sum never exceeds total_qty
    - leftover from rounding is added to first part
    Returns a list of float numbers.
    """
    total_qty = Decimal(str(total_qty))
    min_qty = Decimal(str(min_qty))
    step = Decimal(str(step or min_qty))

    if min_qty <= 0:
        raise ValueError("min_qty must be > 0")
    if total_qty <= 0:
        return [0.0] * len(weights)

    weights_d = [Decimal(str(w)) for w in weights]
    total_weight = sum(weights_d)
    if total_weight <= 0:
        raise ValueError("sum of weights must be > 0")

    # کل واحدها بر حسب step
    total_units = int((total_qty / step).to_integral_value(rounding=ROUND_FLOOR))
    if total_units == 0:
        return [0.0] * len(weights)

    # تقسیم وزن‌ها
    raw_units = [(w * Decimal(total_units) / total_weight) for w in weights_d]
    int_units = [int(u.to_integral_value(rounding=ROUND_FLOOR)) for u in raw_units]

    allocated = sum(int_units)
    remainder_units = total_units - allocated

    # اضافه کردن باقی‌مانده به اولین بخش
    if remainder_units > 0:
        int_units[0] += remainder_units

    # تبدیل واحدها به مقدار qty واقعی
    parts = [float(Decimal(u) * step) for u in int_units]

    # اطمینان از اینکه هیچ مقداری کمتر از min_qty نیست
    parts = [p if p >= float(min_qty) else float(min_qty) for p in parts]

    return parts


async def createTPOrders(signal) -> List[dict]:
    """
    Create Take-Profit orders based on pre-calculated weights and total position qty.
    Uses splitQtyByWeights_decimal() to ensure valid qty distribution.
    """

    keys = signal.get("keys", {})
    symbol = signal.get("symbol")
    side = signal.get("side")
    takeProfits = signal.get("takeProfits", [])
    max_trailing = signal.get("maxTrailing")
    tp_orders = []
    n = len(takeProfits)
    total_qty = await getPositionQty(signal)
    min_qty = Decimal(str(signal.get("minQty", "0.001")))
    weights = generateRatioList(n)

    # ✅ split total qty according to weights (ensures correct rounding)
    splitted_qty = splitQtyByWeights(total_qty, weights, min_qty)

    await adminReport(f"⚖️ Split total qty={total_qty} into {splitted_qty}")

    # loop through TP levels
    for idx, (tp_price, qty) in enumerate(zip(takeProfits, splitted_qty)):
        tp_price = Decimal(str(tp_price))
        qty = Decimal(str(qty))

        if qty <= 0:
            continue

        await adminReport(
            f"TP{idx+1}: price={tp_price}, qty={qty}, weight={weights[idx]}"
        )

        order = copy.deepcopy(signal_template)
        order.update(
            {
                "session": signal.get("session"),
                "demo": signal.get("demo"),
                "exchangeURL": signal.get("exchangeURL"),
                "keys": keys,
                "variant": f"TP{idx+1}",
                "symbol": symbol,
                "side": "Sell" if side == "Buy" else "Buy",
                "orderType": "Limit",
                "qty": str(qty),
                "price": str(tp_price),
                "reduceOnly": True,
            }
        )

        # ✅ last TP: enable trailing stop or close on trigger
        if idx == n - 1:
            order["closeOnTrigger"] = True
            order["trailingStop"] = float(max_trailing or 0.2)

        # remove None values
        order = {k: v for k, v in order.items() if v is not None}
        tp_orders.append(order)

    # ✅ Ensure total qty matches exactly total_qty
    total_alloc = sum(Decimal(o["qty"]) for o in tp_orders)
    diff = Decimal(str(total_qty)) - total_alloc
    if diff != 0 and tp_orders:
        tp_orders[0]["qty"] = str(
            (Decimal(tp_orders[0]["qty"]) + diff).quantize(Decimal(str(min_qty)))
        )
        await adminReport(f"Adjusted first TP qty by {diff} to fix rounding.")

    # await adminReport(f"✅ Created {len(tp_orders)} TP orders for {symbol}:\n{tp_orders}")

    return tp_orders


async def placeSignalOrder(signal: dict) -> dict:
    """
    Place an order on Bybit directly from the given signal
    without modifying the input signal in any way.
    """
    # await adminReport(f"Placing order for signal:\n {signal}")
    
    session = signal.get("session")

    baseURL = signal.get("exchangeURL")
    endPoint = "/v5/order/create"
    url = baseURL + endPoint

    api_key, api_secret = getSecretsFromSignal(signal)
    if not api_key or not api_secret:
        await adminReport("❌ Missing API keys in signal")
        return None

    variant = signal.get("variant")
    if not variant:
        await adminReport("❌ Missing variant in signal")
        return None

    symbol = signal.get("symbol")
    if not symbol:
        await adminReport("❌ Missing symbol in signal")
        return None

    qty = signal.get("qty")
    if not qty:
        await adminReport(f"⚠️ No qty defined for {symbol}, skipping order.")
        return None

    order_type = signal.get("orderType", "Limit")
    entry_price = signal.get("price")  # None for Market orders

    payload = {
        "api_key": api_key,
        "symbol": symbol,
        "side": signal.get("side"),
        "qty": qty,
        "price": entry_price,
        "orderType": order_type,
        "category": signal.get("category", "linear"),
        "timeInForce": signal.get("timeInForce", "GTC"),
        "reduceOnly": signal.get("reduceOnly", False),
        "closeOnTrigger": signal.get("closeOnTrigger", False),
        "marginMode": signal.get("margin_mode", "isolated"),
        "timestamp": await getBybitServerTimeMS(session, baseURL),
        "recv_window": 20000,
    }
    
    # if stopLossFlag:
    #     payload["stopLoss"] = signal.get("stopLoss")

    # Cleanup None values
    payload = {k: v for k, v in payload.items() if v is not None}

    # Sign
    payload["sign"] = signRequest(payload, api_secret)

    # Send request
    res = await _aio_post(session, url, payload)

    if not res or res.get("retCode") != 0:
        await adminReport(f"❌ Order failed for {symbol}: {res}")
        return None

    order_id = res.get("result", {}).get("orderId")
    placed_time = res.get("time") or await getBybitServerTimeMS(session, baseURL)


    return {
        "response": res.get("retCode"),
        "order_id": order_id,
        "price": entry_price,
        "qty": str(qty),
        "time": placed_time,
        "status": "placed",
    }


# --- Place main bybit order based on a signal ---
async def placeBybitOrder(signal: dict) -> dict:
    """Main entry to place an order from a signal. Returns dict with status and updated signal."""
    session_timeout = aiohttp.ClientTimeout(total=30)
    async with aiohttp.ClientSession(timeout=session_timeout) as session:
        try:
            signal["session"] = session

            # From DB
            signal["demo"] = True
            # api_key =
            # api_secret =

            apiKey, apiSecret = getSecretsFromSignal(signal)

            if not apiKey or not apiSecret:
                return {"error": "No API key/secret provided", "signal": signal}

            source = signal.get("source", "unknown")
            symbol = signal["symbol"]

            # Validate and normalize signal
            signal, validation = await isValidSignal(signal)
            if not validation:
                return {"error": "invalid_signal", "signal": signal}

            await adminReport(f"✅ Valid signal detected for {symbol} from {source}.")

            # ✅ Set margin mode and leverage
            demo = signal.get("demo")
            if not demo:  # skip in demo mode, not supported in demo accounts
                try:
                    mlRres = await setMarginAndLeverage(signal=signal)
                    await adminReport(f"⚙️ Margin/Leverage set response: {mlRres}")
                except Exception as e:
                    await adminReport(f"⚠️ Failed to set margin/leverage: {e}")

            # Get symbol rules
            symbolRules = await getSymbolRules(signal)

            signal["minQty"] = symbolRules.get("min_qty", "")
            signal["maxQty"] = symbolRules.get("max_qty", "")
            signal["step"] = symbolRules.get("step", "")
            signal["maxTrailing"] = symbolRules.get("max_trailing", "")

            usdtQty = await getTradeAamountFromBalance(
                signal
            )  # returns string like "50.00"

            if Decimal(str(usdtQty)) <= Decimal("0"):
                await adminReport("❌ Trade amount calculated as 0 - aborting")
                signal["status"] = "error"
                return {"error": "trade_amount_zero", "signal": signal}

            signal["qty"] = usdtQty  # set qty in signal for record

            signal.setdefault("extra_orders", [])

            # main + alt signals
            signals = await signalDivider(signal)

            if signals:
                mainSignal = signals[0]  # Main signal (nearest entry to market)
                altSignals = signals[1:]  # Other alt signals
                
            # List to store placed orders
            placedOrders = []

            # Place main signal first (if exists)
            if (
                mainSignal
                and mainSignal.get("stopLoss")
                and mainSignal.get("takeProfits")
            ):
                order = await placeSignalOrder(mainSignal)

                if order and order.get("response") == 0:
                    mainSignal["order_id"] = order["order_id"]
                    mainSignal["order_timestamp"] = order["time"]
                    mainSignal["status"] = "ordered"

                    executedPosition = await getPosition(mainSignal)
                    executedOrders = await getOpenOrders(signal)
                    
                    # await adminReport(f"Executed Position is:\n{executedPosition}" if executedPosition else f"No Executed Position")
                    # await adminReport(f"Ordered Position is:\n{executedOrders}" if executedOrders else f"No Ordered Position")

                    if executedPosition:
                        mainSignal["execPrice"] = executedPosition.get(
                            "avgPrice", 0.0
                        )
                        mainSignal["status"] = "placed"

                    placedOrders.append(mainSignal)

                    # Place alt signals
                    for altSig in altSignals:
                        order = await placeSignalOrder(altSig)
                        if order and order.get("response") == 0:
                            altSig["order_id"] = order["order_id"]
                            altSig["order_timestamp"] = order["time"]
                            altSig["status"] = "ordered"

                            executedPosition = await getPosition(altSig)
                            # executed_orders = await getOpenOrders(signal)

                            if executedPosition:
                                altSig["execPrice"] = executedPosition.get(
                                    "avgPrice", 0.0
                                )
                                altSig["status"] = "placed"

                            placedOrders.append(altSig)
                        # else:
                        #     await adminReport(f"❌ Failed to place alt order: {altSig}")

                    # executed_orders = await getOpenOrders(signal)
                # await adminReport(
                #     f"✅ Placed {len(placedOrders)} orders for {symbol}.\n Orders: {placedOrders}"
                # )
                
                await saveTradeSnapshot(placedOrders)

                await adminReport(" ✅ Signal execution complete.")
            return {"ok": True, "signal": signal}

        except Exception as e:
            signal["error"] = str(e)
            signal["status"] = "error"
            await adminReport(f"❌ Error in place_bybit_order: {e}")
            return {"error": str(e), "signal": signal}


# --- If run as script for testing (not executed in production) ---
if __name__ == "__main__":
    print("This module is intended to be imported and used asynchronously.")
    
    
    
                    # takeProfits = signal.get("takeProfits")
                    # if not takeProfits:
                    #     await adminReport("❌ Missing takeProfits in signal")
                    #     return None

                    # tp_orders = await createTPOrders(signal)
                    # if tp_orders:
                    #     for tp_order in tp_orders:
                    #         tp_res = await placeSignalOrder(tp_order)
                    #         if tp_res and tp_res.get("response") == 0:
                    #             mainSignal.setdefault("extra_orders", []).append(tp_res.get("order_id"))
                    #             placedOrders.append(tp_res)
                    #         else:
                    #             await adminReport(f"❌ Failed to place TP order: {tp_order}")
                    # else:
                    #     await adminReport("⚠️ No TP orders created based on current position.")

                    # mainSignal["takeProfits"] = signal.get("takeProfits")
                    # mainSignal["order_id"] = order["order_id"]
                    # mainSignal["order_timestamp"] = order["time"]
                    # mainSignal["status"] = "placed"
                    # placedOrders.append(mainSignal)    
