async def saveTradeSnapshot(placedOrders: list):
    """
    Save trade snapshot (State Machine ready).
    """

    savePath = "./logs/trades.json"
    os.makedirs(os.path.dirname(savePath), exist_ok=True)

    # -----------------------------
    # Load existing file
    # -----------------------------
    if os.path.exists(savePath):
        try:
            with open(savePath, "r", encoding="utf-8") as f:
                allTrades = json.load(f)
        except Exception:
            allTrades = {}
    else:
        allTrades = {}

    if not placedOrders:
        raise ValueError("placedOrders is empty")

    mainOrder = next(
        (o for o in placedOrders if o["variant"] == "main"),
        None,
    )

    if not mainOrder:
        raise ValueError("Main order not found")

    symbol = mainOrder["symbol"]

    entries = []
    totalQty = 0.0

    # -----------------------------
    # Build entries
    # -----------------------------
    for order in placedOrders:

        qty = float(order.get("qty") or 0)
        price = float(order.get("price") or 0)

        totalQty += qty

        entries.append(
            {
                "variant": order["variant"],
                "price": price,
                "qty": qty,

                "orderId": order["order_id"],

                # updated by syncTradeState()
                "filled": False,
                "cancelled": False,

                "fillPrice": None,
                "fillQty": 0.0,
            }
        )

    # -----------------------------
    # Qty
    # -----------------------------
    step = float(mainOrder["step"])
    totalQty = float(floorToStepDec(totalQty, step))

    # -----------------------------
    # Take Profits
    # -----------------------------
    takeProfits = [
        float(tp)
        for tp in (mainOrder.get("takeProfits") or [])
    ]
    
    

    if mainOrder["side"].lower() == "buy":
        takeProfits.sort()
    else:
        takeProfits.sort(reverse=True)

    tpOrders = []

    for i, tp in enumerate(takeProfits):

        tpOrders.append(
            {
                "index": i,

                "price": tp,

                # later generated by allocate_tp_qtys()
                "qty": None,

                "orderId": None,

                "placed": False,
                "filled": False,
                "cancelled": False,
            }
        )

    stopLoss = float(mainOrder.get("stopLoss") or 0)

    tradeSummary = {

        # ---------------------------------------------------
        # Identification
        # ---------------------------------------------------
        "symbol": symbol,
        "source": mainOrder["source"],

        "side": mainOrder["side"],

        "state": "waiting_entry",

        # ---------------------------------------------------
        # Exchange info
        # ---------------------------------------------------
        "category": mainOrder["category"],
        "marginMode": mainOrder["margin_mode"],
        "leverage": mainOrder["leverage"],

        # ---------------------------------------------------
        # Instrument limits
        # ---------------------------------------------------
        "minQty": float(mainOrder["minQty"]),
        "maxQty": float(mainOrder["maxQty"]),
        "step": float(mainOrder["step"]),
        "maxTrailing": float(mainOrder["maxTrailing"]),

        # ---------------------------------------------------
        # Planned Trade
        # ---------------------------------------------------
        "entry": float(mainOrder["price"]),

        "qty": totalQty,

        "entries": entries,

        # ---------------------------------------------------
        # Current Position
        # Filled later from Bybit
        # ---------------------------------------------------
        "position": {
            "opened": False,
            "qty": 0.0,
            "avgPrice": None,
            "side": None,
        },

        # ---------------------------------------------------
        # Stop Loss
        # ---------------------------------------------------
        "SLPrice": stopLoss,
        "SLNow": stopLoss,

        "slOrderId": None,

        # ---------------------------------------------------
        # Take Profits
        # ---------------------------------------------------
        "tpIndexHit": 0,

        "tpOrders": tpOrders,

        # ---------------------------------------------------
        # Metadata
        # ---------------------------------------------------
        "createdAt": datetime.now(timezone.utc).isoformat(),

        "updatedAt": datetime.now(timezone.utc).isoformat(),
    }

    allTrades[symbol] = tradeSummary
    
    await adminReport(f"All trades for save is: \n{allTrades}")

    with open(savePath, "w", encoding="utf-8") as f:
        json.dump(
            allTrades,
            f,
            indent=2,
            ensure_ascii=False,
        )

    await adminReport(f"✅ Trade {symbol} saved.")

    return tradeSummary


# async def saveTradeSnapshot(placedOrders: list):
#     """
#     Save trade snapshot (STATE-BASED STRUCTURE v2)
#     """

#     savePath = "./logs/trades.json"
#     os.makedirs(os.path.dirname(savePath), exist_ok=True)

#     # -----------------------------
#     # Load existing trades
#     # -----------------------------
#     if os.path.exists(savePath):
#         try:
#             with open(savePath, "r", encoding="utf-8") as f:
#                 allTrades = json.load(f)
#         except Exception:
#             allTrades = {}
#     else:
#         allTrades = {}

#     if not placedOrders:
#         raise ValueError("placedOrders is empty")

#     mainOrder = next(
#         (o for o in placedOrders if o.get("variant") == "main"),
#         None
#     )

#     if not mainOrder:
#         raise ValueError("Main order not found")

#     symbol = mainOrder["symbol"]

#     # -----------------------------
#     # Build entries
#     # -----------------------------
#     entries = []
#     totalQty = 0.0

#     for order in placedOrders:
#         qty = float(order.get("qty") or 0)
#         price = float(order.get("price") or 0)

#         totalQty += qty

#         entries.append({
#             "variant": order.get("variant"),
#             "price": price,
#             "qty": qty,
#             "orderId": order.get("order_id")
#         })

#     # -----------------------------
#     # Normalize qty
#     # -----------------------------
#     step = float(mainOrder["step"])
#     totalQty = float(floorToStepDec(totalQty, step))

#     # -----------------------------
#     # TakeProfits normalization
#     # -----------------------------
#     takeProfits = [
#         float(tp)
#         for tp in (mainOrder.get("takeProfits") or [])
#     ]

#     if mainOrder["side"].lower() == "buy":
#         takeProfits.sort()
#     else:
#         takeProfits.sort(reverse=True)

#     # -----------------------------
#     # StopLoss
#     # -----------------------------
#     stopLoss = float(mainOrder.get("stopLoss") or 0)

#     # -----------------------------
#     # Final structure (NEW)
#     # -----------------------------
#     tradeSummary = {
#         "symbol": symbol,

#         "source": mainOrder.get("source"),
#         "side": mainOrder.get("side"),
#         "category": mainOrder.get("category"),
#         "marginMode": mainOrder.get("margin_mode"),
#         "leverage": mainOrder.get("leverage"),

#         "minQty": float(mainOrder["minQty"]),
#         "maxQty": float(mainOrder["maxQty"]),
#         "step": step,

#         "state": "waitingEntry",

#         "entry": float(mainOrder["price"]),
#         "qty": totalQty,

#         "entries": entries,

#         "position": {
#             "exists": False,
#             "qty": 0.0,
#             "avgPrice": None,
#             "side": None,
#             "updatedAt": None
#         },

#         "stopLoss": {
#             "initial": stopLoss,
#             "current": stopLoss,
#             "orderId": None
#         },

#         "takeProfits": takeProfits,

#         "tpState": {
#             "index": 0,
#             "orders": []
#         },

#         "runtime": {
#             "createdAt": datetime.now(timezone.utc).isoformat(),
#             "updatedAt": None,
#             "lastSync": None,
#             "lastAction": None
#         }
#     }

#     # -----------------------------
#     # Save
#     # -----------------------------
#     allTrades[symbol] = tradeSummary

#     with open(savePath, "w", encoding="utf-8") as f:
#         json.dump(allTrades, f, indent=2, ensure_ascii=False)

#     await adminReport(f"✅ Trade {symbol} saved (v2 structure).")

#     return tradeSummary


# async def saveTradeSnapshot(placedOrders: list):
#     """
#     Save only essential trade information.
#     """

#     savePath = "./logs/trades.json"
#     os.makedirs(os.path.dirname(savePath), exist_ok=True)
    
#     # Load existing trades
#     if os.path.exists(savePath):
#         try:
#             with open(savePath, "r", encoding="utf-8") as f:
#                 allTrades = json.load(f)
#         except Exception:
#             allTrades = {}
#     else:
#         allTrades = {}

#     if not placedOrders:
#         raise ValueError("placedOrders is empty")

#     mainOrder = next(
#         (order for order in placedOrders if order.get("variant") == "main"),
#         None
#     )

#     if not mainOrder:
#         raise ValueError("Main order not found")

#     symbol = mainOrder["symbol"]

#     entries = []
#     alts = []
#     totalQty = 0.0

#     for order in placedOrders:
#         qty = float(order.get("qty") or 0)
#         price = float(order.get("price") or 0)

#         totalQty += qty

#         entries.append({
#             "variant": order["variant"],
#             "price": price,
#             "qty": qty,
#             "orderId": order["order_id"]
#         })
        
#         if order.get("variant") != "main":
#             alts.append(float(order["entry"][0]))
        
#     # Adjust total qty to step
#     step =  float(mainOrder["step"])
#     totalQty = str(floorToStepDec(totalQty, step))

#     takeProfits = [
#         float(tp)
#         for tp in (mainOrder.get("takeProfits") or [])
#     ]
    
#     if mainOrder["side"].lower() == "buy":
#         takeProfits.sort()
#     else:
#         takeProfits.sort(reverse=True)

#     stopLoss = float(mainOrder.get("stopLoss") or 0)

#     tradeSummary = {
#         "symbol": symbol,
#         "side": mainOrder["side"],
#         "entry": float(mainOrder["price"]),
#         "qty": totalQty,
        
#         "minQty": float(mainOrder["minQty"]),
#         "maxQty": float(mainOrder["maxQty"]),
#         "step": float(mainOrder["step"]),
#         "maxTrailing": float(mainOrder["maxTrailing"]),

#         "leverage": mainOrder["leverage"],
#         "marginMode": mainOrder["margin_mode"],
#         "category": mainOrder["category"],
#         "source": mainOrder["source"],

#         "takeProfits": takeProfits,
#         "tpIndexHit": 0,

#         "SLPrice": stopLoss,
#         "SLNow": stopLoss,
        
#         "alts": alts,
#         "altsHit": 0,

#         "entries": entries,

#         "createdAt": datetime.now(timezone.utc).isoformat()
#     }

#     allTrades[symbol] = tradeSummary

#     with open(savePath, "w", encoding="utf-8") as f:
#         json.dump(allTrades, f, indent=2, ensure_ascii=False)

#     await adminReport(f"✅ Trade {symbol} saved.")

#     return tradeSummary
